server:
  port: 9915

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

# Spring health monitoring
management:
  health:
    jms:
     enabled: false

backbase:
  security:
    mtls:
      enabled: false
    public:
      paths:
        - "/**"

buildingblocks:
  security:
    csrf:
      autoconfig: true
      enabled: false

security:
  disabled: true

spring:
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-persistence-legacy.xml"
    enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    # Strongly recommend to set this property to "none"
    # production environment!
    hibernate.ddl-auto: none
  datasource:
    ## You often do not need to specify the driver-class-name,
    ## since Spring Boot can deduce it for most databases from the url.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/product?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
    username: root
    password: backbase
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
