openapi: 3.0.1
info:
  title: Review Service API
  description: Description of the API...
  termsOfService: http://atorres.es
  contact:
    name: Contact
    url: http://atorres.es
    email: me@mail.com
  license:
    name: Copyright Backbase
    url: https://www.backbase.com/legal
  version: 1.0.0
servers:
  - url: http://localhost:8080/
tags:
  - name: review-service-impl
    description: REST API for review information.
paths:
  /service-api/v1/products/{productId}/reviews:
    get:
      tags:
        - review-service-impl
      summary: Returns a list of reviews by Product Id
      description: |
      operationId: getReviewListByProductId
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewList'
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
    delete:
      tags:
        - review-service-impl
      summary: Delete all product reviews.
      description: |
      operationId: deleteReviewsByProductId
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: OK
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
  /service-api/v1/reviews:
    post:
      tags:
        - review-service-impl
      summary:  Create a review
      description: |
      operationId: postReview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '204':
          description: If the transactions have been created and/or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewId'
    put:
      tags:
        - review-service-impl
      summary:  Update a review
      description: |
      operationId: putReview
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '204':
          description: If the transactions have been created and/or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewId'
  /service-api/v1/reviews/{reviewId}:
    get:
      tags:
        - review-service-impl
      summary: Returns a view of the specified review id
      description: |
      operationId: getReviewUsingGET
      parameters:
        - name: reviewId
          in: path
          description: reviewId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
    delete:
      tags:
        - review-service-impl
      summary: Deletes a review
      description: |
      operationId: deleteReview
      parameters:
        - name: reviewId
          in: path
          description: reviewId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: OK
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
components:
  schemas:
    Review:
      title: Review
      type: object
      properties:
        reviewId:
          type: integer
          format: int64
        productId:
          type: integer
          format: int64
        author:
          type: string
        content:
          type: string
        subject:
          type: string
    ReviewList:
      title: ReviewList
      description: An array of reviews
      type: array
      items:
        $ref: '#/components/schemas/Review'
      required:
        - ReviewList
    ReviewId:
      type: object
      description: Object that defines an id attribute only.
      properties:
        id:
          description: Internally used unique identification
          type: integer
          format: int64
      required:
        - id
