apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: golden-sample
  description: This project is a development of a small set of [Backbase Service SDK](https://community.backbase.com/documentation/ServiceSDK/latest/index) (**Spring Boot** and **Cloud**) based Microservices projects that implement cloud-native intuitive, Microservices design patterns, and coding best practices.
  tags:
    - java
    - spring
    - ssdk
  links:
    - url: https://100daysof.backbase.com/ssdk/golden-sample.html
      title: Community
      icon: user
    - url: https://github.com/Backbase/golden-sample-services/wiki
      title: Confluence space
      icon: group
    - url: https://github.com/Backbase/golden-sample-services/pkgs/container/golden-sample%2Fproduct
      title: Docker image
      icon: cloud
    - url: https://github.com/Backbase/golden-sample-services/tree/main/charts
      title: Helm Chart
      icon: dashboard
    - url: https://backbase.slack.com/archives/CG2C5NH8D
      title: Support channel
      icon: help
spec:
  type: service
  lifecycle: production
  owner: backend-guild
