openapi: 3.0.1
info:
  title: Product Service API
  description: Description of the API...
  termsOfService: http://atorres.es
  contact:
    name: Contact
    url: http://atorres.es
    email: me@mail.com
  license:
    name: Copyright Backbase
    url: https://www.backbase.com/legal
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: product-service-impl
    description: REST API for product information.
paths:
  /service-api/v1/products:
    get:
      tags:
        - product-service-impl
      summary: Returns a composite view of the specified product id
      description: |
        # Normal response
        If the requested product id is found the method will return information regarding:
        1. Base product information
        1. Reviews

        # Expected partial and error responses
        In the following cases, only a partial response be created (used to simplify testing of error conditions)

        ## Product id 113
        200 - Ok, but no recommendations will be returned

        ## Product id 213
        200 - Ok, but no reviews will be returned

        ## Non numerical product id
        400 - A <b>Bad Request</b> error will be returned

        ## Product id 13
        404 - A <b>Not Found</b> error will be returned

        ## Negative product ids
        422 - An <b>Unprocessable Entity</b> error will be returned
      operationId: getProductListUsingGET
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
    post:
      tags:
        - product-service-impl
      summary:  Create a product
      description: |
      operationId: postProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: If the transactions have been created and/or updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductId'
    put:
      tags:
        - product-service-impl
      summary:  Update a product
      description: |
      operationId: putProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: OK
  /service-api/v1/products/{productId}:
    get:
      tags:
        - product-service-impl
      summary: Returns a composite view of the specified product id
      description: |
      operationId: getProductUsingGET
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
    delete:
      tags:
        - product-service-impl
      summary: Deletes a product
      description: |
      operationId: deleteProduct
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        201:
          description: OK
        400:
          description: Bad Request, invalid format of the request. See response message
            for more information.
          content: {}
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not found, the specified id does not exist.
          content: {}
        422:
          description: Unprocessable entity, input parameters caused the processing
            to fails. See response message for more information.
          content: {}
  /service-api/v2/products/{productId}:
    put:
      tags:
        - product-service-impl
      summary:  Update a product
      description: |
      operationId: putProductById
      parameters:
        - name: productId
          in: path
          description: productId
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: OK
components:
  schemas:
    Product:
      title: Product
      type: object
      properties:
        name:
          type: string
        productId:
          type: integer
          format: int64
        weight:
          type: integer
          format: int32
        createDate:
          description: The date when the product was created
          type: string
          format: date
    ProductList:
      title: ProductList
      description: An array of products
      type: array
      items:
        $ref: '#/components/schemas/Product'
      required:
        - ProductList
    ProductId:
      type: object
      description: Object that defines an id attribute only.
      properties:
        id:
          description: Internally used unique identification
          type: integer
          format: int64
      required:
        - id
