type: object
properties:
  name:
    type: string
  productId:
    type: integer
    format: int64
  reviews:
    type: array
    items:
      $ref: '../schemas/definitions.yaml#/components/schemas/ReviewSummary'
  weight:
    type: integer
    format: int32
  createDate:
    description: The date when the product was created
    type: string
    format: date
  additions:
    $ref: '../schemas/definitions.yaml#/components/schemas/Additions'
