POST http://localhost:9916/service-api/v1/reviews/
Content-Type: application/json

{ "productId":  "1",
  "author": "author",
  "subject":  "great",
  "content":  "best product ever" }

###
GET http://localhost:9916/service-api/v1/products/1/reviews/

###
PUT http://localhost:9916/service-api/v1/reviews
Content-Type: application/json

{ "reviewId" : "1",
  "productId" : "1",
  "author": "author",
  "subject":  "great",
  "content":  "worst product ever" }

###
GET http://localhost:9916/service-api/v1/reviews/1

###
DELETE http://localhost:9916/service-api/v1/reviews/1

###
DELETE http://localhost:9916/service-api/v1/products/1/reviews


