extends: spectral:oas
rules:
  api-servers:
    description: "OpenAPI `servers` must be present and non-empty array."
    severity: error
    formats: ["oas3"]
    given: "$"
    then:
      field: servers
      function: schema
      functionOptions:
        schema:
          items:
            type: object
          minItems: 1
          type: array
  mock-api-server:
    description: "Mock API server must be the first one so that Postman import uses it."
    severity: error
    formats: ["oas3"]
    given: "$.servers[0].url"
    then:
      function: pattern
      functionOptions:
        match: "http://localhost:4010"
  camel-case-operationId:
    description: "OperationId must be camelCase in order to generate good method names"
    severity: error
    given: "$.paths.*.*.operationId"
    then:
      function: pattern
      functionOptions:
        match: '^[a-z]+((\d)|([A-Z0-9][a-z0-9]+))*([A-Z])?$'
  request-body-references-reusable-components:
    description: "$ref may only point to examples or elements in the components section of openapi.yaml to generate good class names"
    severity: error
    resolved: false
    given: "$..requestBody..*.$ref"
    then:
      function: pattern
      functionOptions:
        match: '^.*\#\/components\/schemas.*|examples.*$'
  response-references-reusable-components:
    description: "$ref may only point to examples or elements in the components section of openapi.yaml to generate good class names"
    severity: error
    resolved: false
    given: "$..responses..*.$ref"
    then:
      function: pattern
      functionOptions:
        match: '^.*\#\/components\/schemas.*|^.*\#\/components\/headers.*|examples.*$'
  examples-responses-are-valid:
    message: "{{error}}"
    severity: error
    given: "$..responses..[?(@property !== 'properties' && @.examples)]"
    then:
      function: schemaPath
      functionOptions:
        field: "$.examples.*.value"
        schemaPath: "$.schema"
  info-contact: false
  example-value-or-externalValue: false
  openapi-tags-alphabetical: error
  oas3-server-not-example.com: error
  oas3-parameter-description: error
