
CREATE TABLE product (id BIGINT AUTO_INCREMENT NOT NULL, create_date datetime NOT NULL, name VARCHAR(255) NULL, weight SMALLINT NULL, CONSTRAINT PK_PRODUCT PRIMARY KEY (id, create_date))
PARTITION BY RANGE COLUMNS (create_date) ( PARTITION p0 VALUES LESS THAN ('2019-01-01'), PARTITION p1 VALUES LESS THAN ('2020-01-01'), PARTITION p2 VALUES LESS THAN ('2021-01-01'));

CREATE INDEX idx_create_date ON product(create_date DESC);

