apiVersion: v2
name: review
# Custom property used by Backbase internal tooling. If the field is not present (= default),
# or value public=true means it’s a public Chart, it should be released to customers. If false, it should not go outside and keep it only internal
public: true
description: A Helm chart for the Review service
version: 0.1.0
# https://helm.sh/docs/topics/charts/#the-appversion-field
appVersion: ">= 1.0.0"
# https://helm.sh/docs/topics/charts/#the-kubeversion-field
kubeVersion: ">= 1.18.0"
keywords:
  - golden-sample
  - review
dependencies:
  - name: backbase-app
    repository: https://repo.backbase.com/backbase-charts
    version: 0.18.3
    alias: review
maintainers:
  - name: backbase
    email: backbase@backbase.com
icon: https://start.backbase.com/favicon.png
