type: object
properties:
  name:
    type: string
  productId:
    type: integer
    format: int64
  weight:
    type: integer
    format: int32
  createDate:
    description: The date when the product was created
    type: string
    format: date
  responsive:
    type: boolean
    description: True if the slot is responsive; false otherwise.
    default: false
    example: false
  additions:
    $ref: '../schemas/definitions.yaml#/components/schemas/Additions'
