server:
  port: 9917
  error:
    include-message: always

# API Registry client configuration
eureka:
  instance:
    metadata-map:
      public: true
      role: live
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8080/registry/eureka/

# Configure Internal JWT handler
sso:
  jwt:
    internal:
      signature:
        key:
          type: ENV
          value: SIG_SECRET_KEY

backbase:
  # No service discovery setup
  product-service:
    serviceId: localhost
    servicePort: 9915
  review-service:
    serviceId: localhost
    servicePort: 9916
  store:
    theme: original
    theme@tid(rebrand_shop): rebranded
    extensions:
      product-enricher:
        enabled: false
#        ignoreErrorResponse: true  -   Configure how to handle errors
#        client:
#          service-id:                  Configure service id when enabled.
  security:
    mtls:
      enabled: false
    public:
      paths:
        - "/**"

# Spring health monitoring
management:
  health:
    jms:
     enabled: false

logging:
  level:
    root: INFO
    com.backbase.goldensample: DEBUG
