backbase:
  context:
    error-on-invalid-property-name: false
  multi-tenancy:
    enabled: true
    tenants:
      - id: org_shop
      - id: rebrand_shop
  api:
    extensions:
      classes:
        com.backbase.goldensample.store.api.service.v2.model.ProductAggregate: ext-product
        com.backbase.goldensample.store.api.service.v2.model.ReviewSummary: ext-review
      property-sets:
        ext-product:
          properties:
            - property-name: popularity
        ext-review:
          properties:
            - property-name: verified
