type: object
properties:
  name:
    type: string
  productId:
    type: integer
    format: int64
  weight:
    type: integer
    format: int32
  createDate:
    description: The date when the product was created
    type: string
    format: date
required:
  - productId
