package com.backbase.goldensample.review.persistence;

import com.backbase.goldensample.review.config.IdentityStrategyOverrideConfiguration;
import java.util.Map;
import java.util.Objects;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;
import lombok.Setter;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.hibernate.annotations.GenericGenerator;

@Entity
@Table(
    name = "review",
    indexes = {
        @Index(name = "review_unique_idx", unique = true, columnList = "productId, id")
    })
@Getter
@Setter
@Builder
@AllArgsConstructor
public class ReviewEntity {

    /**
     *
     *
     * <p>Primary key is generated with {@link GenerationType#SEQUENCE} for every database except MySql which does not
     * support sequences.</p> <p>For MySql the generation strategy is overridden to be {@link
     * GenerationType#IDENTITY}.</p>
     *
     * @see IdentityStrategyOverrideConfiguration
     */
    @Id
    @GenericGenerator(
        name = "sequenceGenerator",
        strategy = "enhanced-sequence",
        parameters = {
            @org.hibernate.annotations.Parameter(
                name = "optimizer",
                value = "pooled-lo"
            ),
            @org.hibernate.annotations.Parameter(
                name = "initial_value",
                value = "1"
            ),
            @org.hibernate.annotations.Parameter(
                name = "increment_size",
                value = "5"
            ),
            @org.hibernate.annotations.Parameter(
                name = "sequence_name",
                value = "hibernate_sequence"
            )
        }
    )
    @GeneratedValue(
        strategy = GenerationType.SEQUENCE,
        generator = "sequenceGenerator"
    )
    private Long id;

    @NonNull
    private Long productId;
    @NonNull
    @NotBlank
    @Size(min = 6, max = 50)
    private String author;
    @NonNull
    @NotBlank
    private String subject;
    @NonNull
    @NotBlank
    private String content;
    private Integer stars;

    @Lob
    @Column(name = "additions", columnDefinition = "CLOB")
    @Convert(converter = MapToJsonConverter.class)
    private Map<String, String> additions = Map.of();

    //No-Op
    public ReviewEntity() {
    }

    public ReviewEntity(Long productId, String author, String subject, String content, Integer stars, Map<String, String> additions) {
        this.productId = productId;
        this.author = author;
        this.subject = subject;
        this.content = content;
        this.stars = stars;
        this.additions = additions;
    }

    /**
     * This equal method will guarantee equality by its primary key identifier. If the entity hasn't been persisted yet,
     * and id is null, we won't be able to check its equality with other entities, so it will be always `false`. This
     * implementation will validate the equality of the same entity among different state transitions for entities that
     * doesn't contain a Natural ID and when the ID is autogenerated.
     *
     * @param o - object to be check for equality
     * @return true if both objects are equal
     * @see <a href="https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/">More
     * information about this solution.</a>
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ReviewEntity that)) {
            return false;
        }
        return id != null && Objects.equals(id, that.id);
    }

    /**
     * As we are using the Entity Identifier ( that is autogenerated ) for the equals method, we require a hashcode
     * method that returns the same value every time, regardless the entity has been persisted ( will have an id value )
     * or not ( it won't ).
     *
     * @return a constant Hashcode value
     * @see <a href="https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/">More
     * information about this solution.</a>
     */
    @Override
    public int hashCode() {
        return getClass().hashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("id", id)
            .append("productId", productId)
            .append("author", author)
            .append("subject", subject)
            .append("content", content)
            .append("stars", stars)
            .append("additions", additions)
            .toString();
    }
}
